---
- hosts: all
  become: yes
  tasks:
  - name: include docker
    include: docker.yaml
  - name: repos
    yum:
      name:
      - epel-release
  - name: packages
    yum:
      name:
      - git
      - vim
      - tree
      state: present
  - name: kubernetes repo
    copy:
      src: ./files/kubernetes.repo
      dest: /etc/yum.repos.d/
      mode: preserve
  - name: install control components
    yum:
      name:
      - kubeadm
      state: present
- hosts: '*control'
  become: yes
  tasks:
  - name: kubelet service
    service:
      name: kubelet
      state: started
      enabled: true
