---
- hosts: all
  become: yes
  tasks:

  - name: remove libvirt nameserver
    lineinfile:
      path: /etc/resolv.conf
      regexp: '^nameserver 192.168.122.1'
      state: absent

  - name: Add IP address of all hosts to all hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"

  - name: firewalld is disabled
    systemd: name=firewalld enabled=no state=stopped

  - name: include docker
    include: docker-driver.yaml

  - name: base repos
    yum:
      name:
      - epel-release

  - name: base packages
    yum:
      name:
      - git
      - vim
      - tree
      state: present

  - name: kubernetes repo
    copy:
      src: ./files/kubernetes.repo
      dest: /etc/yum.repos.d/
      mode: preserve

  - name: install control components
    yum:
      name:
      - kubelet
      - kubeadm
      state: present

  - name: docker config
    copy:
      src: ./files/daemon.json
      dest: /etc/docker/daemon.json
    notify:
      - restart docker

  handlers:

    - name: restart docker
      service:
        name: docker
        state: restarted

# ---------------------------------------------

- hosts: 'control'
  become: yes
  tasks:

  - name: bash profile
    copy:
      src: ./files/bash_profile
      dest: /root/.bash_profile

  - name: kubeadm config
    copy:
      src: ./files/kubeadm-config.yaml
      dest: /etc/kubeadm-config.yaml

  - name: kubelet service
    service:
      name: kubelet
      state: started
      enabled: true

  - name: kubeadm init
    command: kubeadm init --config /etc/kubeadm-config.yaml
    args:
      creates: '/etc/kubernetes/admin.conf'
           
  - name: get token 
    shell: "kubeadm token create --print-join-command | tail -1"
    register: join

  - name: set facts
    set_fact:
      join: "{{ join.stdout }}"

# ---------------------------------------------

- hosts: 'worker*'
  become: yes
  tasks:

  - name: join cluster
    command: "{{ hostvars['control']['join'] }}"
    args:
      creates: '/etc/kubernetes/pki/ca.crt'
