---
- hosts: all
  become: yes
  tasks:
  - name: repos
    yum:
      name:
      - epel-release
  - name: packages
    yum:
      name:
      - git
      - vim
      - tree
      - container-selinux
      - selinux-policy-base
      state: present
  - name: docker repo
    copy:
      src: ./files/docker-ce.repo
      dest: /etc/yum.repos.d/
      mode: preserve
  - name: kubernetes repo
    copy:
      src: ./files/kubernetes.repo
      dest: /etc/yum.repos.d/
      mode: preserve
  - name: containerd.conf
    copy:
      src: ./files/containerd.conf
      dest: /etc/modules-load.d/
  - name: load overlay module
    modprobe:
      name: overlay
  - name: load br_netfilter module
    modprobe:
      name: br_netfilter
  - name: sysctl
    copy:
      src: files/99-kubernetes-cri.conf 
      dest: /etc/sysctl.d/
    register: sysctl
  - name: sysctl reload
    shell: sysctl --system
    when: sysctl.changed
  - name: install containerd components
    yum:
      name:
      - containerd.io
      state: present
  - name: containerd service
    service:
      name: containerd
      state: started
      enabled: true
- hosts: '*control'
  become: yes
  tasks:
  - name: install control components
    yum:
      name:
      - kubeadm
      state: present
  - name: kubelet service
    service:
      name: kubelet
      state: started
      enabled: true
